# Global placeholder settings
founderlink.version=1.0.0
management.tracing.enabled=${MANAGEMENT_TRACING_ENABLED:true}
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:19411/api/v2/spans}
